version: '3'
services:
  excursia:
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: excursia
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - 3000:3000
    command: npm run dev